---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/vagrant-os-image-builder
    tag: develop

inputs:
- name: bosh-src

outputs:
- name: bosh-out

run:
  path: bosh-src/build.sh
